### ISSUE TITLE
Invalid integration docker specified for integration type: hub

### ISSUE THREAD

**Issue by magwas** [devops-recipes/node_app#2]
I have created the following shippable.yml based on this repo's example:

```
language: node_js

build:

  ci:
    - docker build -t kodekonveyor/toolchain:$BRANCH.$BUILD_NUMBER .

  post_ci:
    - docker push kodekonveyor/toolchain:$BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: docker
type: dockerRegistryLogin

```

The build output is:
```

   Alerts
  Errors
Invalid integration docker specified for integration type: hub
```

My integration looks like this:

- integration name: docker
- Integration Type: Docker Registry
- Url: https://index.docker.io/v1/
- Username: magwas #my username on hub.docker.com
- Password: <my docker hub password>
- Email: m4gw4s@gmail.com
